export const members = [
  {
    name: 'Executive Committee',
    members: [
      {
        name: 'Mr. Salman Bin Kashif',
        position: 'Chairperson',
        scholar: 'SSGSA Scholar 2014-15',
        university: 'Clemson University',
        place: 'Clemson, SC, USA',
        imageUrl: '/members/SalmanBinKashif.jpg',
      },
      {
        name: 'Mr. Syed Ali Rizvi',
        place: 'Boston, MA, USA',
        imageUrl: '/members/SyedAliRizvi.png',
      },
      {
        name: 'Dr. Saif Sheikh',
        place: 'Chicago, IL, USA',
        imageUrl: '/members/SaifSheikh.jpg',
      },
      {
        name: 'Dr. Rehan Baqri',
        place: 'Boston, MA, USA',
        imageUrl: '/members/RehanBaqri.jpg',
      },
      {
        name: 'Dr. Shaida Andrabi',
        place: 'Srinagar, Jammu and Kashmir, India',
        imageUrl: '/members/ShaidaAndrabi.jpg',
      },
    ],
  },
  {
    name: 'Mentorship and Applications',
    members: [
      {
        name: 'Mr. Shujaut H. Bader',
        position: 'Team Lead',
        scholar: 'SSGSA Scholar 2014-15',
        university: 'Iowa State University',
        place: 'Ames, IA, USA',
        imageUrl: '/members/ShujautHBader.jpg',
      },
      {
        name: 'Mr. Shiva Agarwal',
        position: 'Team Co-Lead',
        scholar: 'SSGSA Scholar 2018-19',
        university: 'Western Michigan University',
        place: 'Kalamazoo, MI, USA',
        imageUrl: '/members/ShivaAgarwal.jpg',
      },
      {
        name: 'Mr. Sajad Sheikh',
        scholar: 'SSGSA Scholar 2016-17',
        university: 'Kent State University',
        place: 'Kent, OH, USA',
        imageUrl: '/members/SajadSheikh.jpeg',
      },
      {
        name: 'Mr. Omar Khursheed',
        scholar: 'SSGSA Scholar 2018-19',
        university: 'Amazon Inc',
        place: 'Sunnyvale, CA, USA',
        imageUrl: '/members/OmarKhursheed.jpeg',
      },
      {
        name: 'Md Ful Hossain Sk',
        scholar: 'SSGSA Scholar 2018-19',
        university: 'Kansas University',
        place: 'Lawrence, KS, USA',
        imageUrl: '/members/FulHossainSk.jpg',
      },
    ],
  },
  {
    name: 'Finance',
    members: [
      {
        name: 'Mr. Ajaharul Islam',
        position: 'Team Lead',
        scholar: 'SSGSA Scholar 2015-16',
        university: 'Kent State University',
        place: 'Kent, OH, USA',
        imageUrl: '/members/AjaharulIslam.jpg',
      },
      {
        name: 'Mr. Sachin Gupta',
        position: 'Team Co-Lead',
        scholar: 'SSGSA Scholar 2017-18',
        university: 'University of Massachusetts, Boston',
        place: 'Boston, MA, USA',
        imageUrl: '/members/SachinGupta.jpeg',
      },
    ],
  },
  {
    name: 'Web Portal',
    members: [
      {
        name: 'Mr. Prateek Jain',
        position: 'Mentor',
        university: 'Aligarh Muslim University',
        place: 'Aligarh, India',
        imageUrl: '/members/PrateekJain.jpg',
      },
      {
        name: 'Mr. Prajjwal Nijhara',
        position: 'Team Lead',
        university: 'Aligarh Muslim University',
        place: 'Aligarh, India',
        imageUrl: '/members/PrajjwalNijhara.jpeg',
      },
      {
        name: 'Mr. Roshan Sharma',
        university: 'Aligarh Muslim University',
        place: 'Aligarh, India',
        imageUrl: '/members/RoshanSharma.jpeg',
      },
      {
        name: 'Mr. Himanshu Varandani',
        university: 'Aligarh Muslim University',
        place: 'Aligarh, India',
        imageUrl: '/members/HimanshuVarandani.jpg',
      },
    ],
  },
  {
    name: 'Promotions',
    members: [
      {
        name: 'Dr. Mohd Zubair',
        position: 'Team Lead',
        scholar: 'SSGSA Scholar 2013-14',
        university: 'Novogene Inc',
        place: 'Raleigh, NC, USA',
        imageUrl: '/members/Zubair.jpg',
      },
      {
        name: 'Ms. Noor Zaidi',
        scholar: 'SSGSA Scholar 2014-15',
        place: 'New Delhi, India',
        imageUrl: '/members/NoorZaidi.jpg',
      },
      {
        name: 'Mr. Kashif Ahmad',
        scholar: 'SSGSA Scholar 2015-16',
        university: 'Tesla Inc.',
        place: 'Reno, NV, USA',
        imageUrl: '/members/KashifAhmad.jpeg',
      },
      {
        name: 'Ms. Ifra Ilyas',
        scholar: 'SSGSA Scholar 2020-21',
        university:
          'Aligarh Muslim University, admitted to Georgetown University, USA',
        place: 'Aligarh, India',
        imageUrl: '/members/IfraIlyas.jpg',
      },
      {
        name: 'Ms. Iqra Fatima',
        scholar: 'SSGSA Scholar 2019-20',
        university: 'Aligarh Muslim University',
        place: 'Aligarh, India',
        imageUrl: '/members/IqraFatima.png',
      },
    ],
  },
  {
    name: 'Outreach',
    members: [
      {
        name: 'Mr. Mohd Toaha Umar',
        position: 'Team Lead',
        scholar: 'SSGSA Scholar 2017-18',
        university: 'Techincal University of Munich',
        place: 'Munich, Germany',
        imageUrl: '/members/ToahaUmar.jpg',
      },
      {
        name: 'Ms. Sadia Tanweer',
        position: 'Diversity, Equity and Inclusion Head',
        scholar: 'SSGSA Scholar 2016-17',
        university: 'University of Oulu',
        place: 'Oulu, Finland',
        imageUrl: '/members/SadiaTanweer.jpg',
      },
      {
        name: 'Mr. Mohd Azhar Hasan Ansari',
        position: 'Campus coordinator',
        scholar: 'SSGSA Scholar 2020-21',
        university:
          'Aligarh Muslim University, admitted to Clemson Univesity, USA',
        place: 'Aligarh, India',
        imageUrl: '/members/AzharHasan.jpg',
      },
    ],
  },
  {
    name: 'Training and Skill Development',
    members: [
      {
        name: 'Dr. Sabahuddin Ahmad',
        position: 'Team Lead',
        scholar: 'ISRA scholar 2013-14',
        university: 'Heinrich Heine University',
        place: 'Duesseldorf, Germany',
        imageUrl: '/members/SabahuddinAhmad.jpeg',
      },
      {
        name: 'Mr. Hashir Ahmad',
        scholar: 'SSGSA Scholar 2018-19',
        university: 'Techincal University of Munich',
        place: 'Munich, Germany',
        imageUrl: '/members/HashirAhmad.png',
      },
      {
        name: 'Haris Ahsan Safdari',
        scholar: 'SSGSA Scholar 2016-17',
        university: 'University of Hamburg',
        place: 'Hamburg, Germany',
        imageUrl: '/members/HarisAhsanSafdari.jpg',
      },
      {
        name: 'Md Ful Hossain Sk',
        scholar: 'SSGSA Scholar 2018-19',
        university: 'Kansas University',
        place: 'Lawrence, KS, USA',
        imageUrl: '/members/FulHossainSk.jpg',
      },
      {
        name: 'Tanwee Kausar',
        scholar: 'SSGSA Scholar 2012-13',
        university: 'San Diego',
        place: 'CA, USA',
        imageUrl: '/members/TanweeKausar.jpg',
      },
    ],
  },
]
