require('dotenv').config()

module.exports = {
  env: {
    EMAILJS_SERVICE_ID: process.env.EMAILJS_SERVICE_ID,
    EMAILJS_TEMPLATE_ID: process.env.EMAILJS_TEMPLATE_ID,
    EMAILJS_USER_ID: process.env.EMAILJS_USER_ID,
    NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY:
      process.env.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY,
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN:
      process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN,
    NEXT_PUBLIC_FIREBASE_PROJECT_ID:
      process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
    NEXT_PUBLIC_QUESTION_1: process.env.NEXT_PUBLIC_QUESTION_1,
    NEXT_PUBLIC_QUESTION_2: process.env.NEXT_PUBLIC_QUESTION_2,
    NEXT_PUBLIC_QUESTION_3: process.env.NEXT_PUBLIC_QUESTION_3,
    NEXT_PUBLIC_QUESTION_4: process.env.NEXT_PUBLIC_QUESTION_4,
    NEXT_PUBLIC_QUESTION_5: process.env.NEXT_PUBLIC_QUESTION_5,
    NEXT_PUBLIC_APPLICATION_START_DATE:
      process.env.NEXT_PUBLIC_APPLICATION_START_DATE,
    NEXT_PUBLIC_APPLICATION_END_DATE:
      process.env.NEXT_PUBLIC_APPLICATION_END_DATE,
    NEXT_PUBLIC_ADMIN_EMAIL: process.env.NEXT_PUBLIC_ADMIN_EMAIL,
  },
  reactStrictMode: true,
}
